name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, primary]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Inject Environment
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TENOR_API_KEY: ${{ secrets.TENOR_API_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: |
          touch .env
          echo BOT_TOKEN=$BOT_TOKEN > .env
          echo CLIENT_ID=$CLIENT_ID >> .env
          echo TENOR_API_KEY=$TENOR_API_KEY >> .env

      - name: Stop Docker
        run: |
          docker stop milk-bot
          docker rm milk-bot
        continue-on-error: true
      - name: Build Docker Image
        run: docker build -t milk-bot .
      - name: Start Docker
        run: docker run -d --name milk-bot --env-file .env milk-bot
